update-all-components-events
mxdi9i7/vant-react pull request #89
Opened 2020-12-22 15:01 UTC by wujingquan

2020-12-22 15:16 UTC, mxdi9i7 requested changes

2020-12-22 15:16 UTC, mxdi9i7 commented on src/components/Field/index.stories.tsx
> +        onInput={(e) => setValue(e.target.value)}
this should probably also be onChange instead of onInput

2020-12-22 15:16 UTC, mxdi9i7 commented on src/components/Search/index.stories.tsx
> +        onInput={(e) => setValue(e.target.value)}
this should be onChange

2020-12-22 15:17 UTC, mxdi9i7 commented
Also remember to update the version number in package.json, upgrade to the next minor version

2020-12-22 15:26 UTC, wujingquan commented
> Also remember to update the version number in package.json, upgrade to the next minor version

Ok, I've updated it.

2020-12-22 16:08 UTC, mxdi9i7 requested changes

2020-12-22 16:08 UTC, mxdi9i7 commented on package.json
> +  "version": "0.2.9",
this is a breaking change, should update the minor version instead of patch version

2020-12-22 16:08 UTC, mxdi9i7 commented on package.json
> +  "version": "0.2.9",
0.3.0

2020-12-23 03:31 UTC, mxdi9i7 approved these changes

2020-12-23 03:32 UTC, merged